# .github/workflows/terraform.yml
name: Terraform Deployment

on:
  push:
    branches: [main, develop]  # Jab bhi push ho
  pull_request:
    branches: [main]           # PR pe bhi chalega

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform  # IMPORTANT: Aapki terraform folder
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0
      
      - name: Terraform Init
        run: terraform init
      
      - name: Terraform Plan
        run: terraform plan
